local Grid = require("tactics_battle.world.Grid")
local Battlefield = require("tactics_battle.world.Battlefield")
local Unit = require("tactics_battle.world.Unit")

describe("Battlefield", function()
    it("adds units to empty tiles", function()
        local grid = Grid.new(4, 4, 32)
        local battlefield = Battlefield.new(grid)
        local unit = Unit.new({ id = "u1", col = 1, row = 1 })
        battlefield:addUnit(unit, 1, 1)
        assertEquals(battlefield:getUnitAt(1, 1), unit)
    end)

    it("moves units to new positions", function()
        local grid = Grid.new(4, 4, 32)
        local battlefield = Battlefield.new(grid)
        local unit = Unit.new({ id = "u1", col = 1, row = 1 })
        battlefield:addUnit(unit, 1, 1)
        battlefield:moveUnit(unit, 2, 2)
        assertTrue(battlefield:getUnitAt(1, 1) == nil)
        assertEquals(battlefield:getUnitAt(2, 2), unit)
    end)

    it("groups units by faction", function()
        local grid = Grid.new(4, 4, 32)
        local battlefield = Battlefield.new(grid)
        local ally = Unit.new({ id = "ally", faction = "allies" })
        local enemy = Unit.new({ id = "enemy", faction = "enemies", col = 2, row = 2 })
        battlefield:addUnit(ally, 1, 1)
        battlefield:addUnit(enemy, 2, 2)
        local groups = battlefield:unitsByFaction()
        assertEquals(#groups.allies, 1)
        assertEquals(#groups.enemies, 1)
    end)
end)
