name: Build love.js Preview

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Lua 5.1
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.1"
          buildCache: "false"

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Ensure Lua compiler is available
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1

      - name: Run Lua unit tests
        run: lua tests/run_tests.lua

      - name: Lint Lua sources
        run: |
          LUAC_EXEC=$(ci_preview/detect_luac.sh)
          find . -type f -name '*.lua' -not -path './vendor/*' -not -path './.lua/*' -print0 | xargs -0 -n1 "$LUAC_EXEC" -p

      - name: Prepare build directories
        run: |
          rm -rf build
          mkdir -p build

      - name: Create tactics battle .love archive
        run: |
          cd tactics_battle
          zip -9 -r ../build/tactics_battle.love .

      - name: Build love.js compatibility runtime
        run: |
          npx --yes love.js -c build/tactics_battle.love build/lovejs --title "Tactics Battle Preview"
          cp build/tactics_battle.love build/lovejs/game.love

      - name: Generate preview HTML shell
        run: lua ci_preview/generate_preview_html.lua --output build/lovejs/index.html --game-archive game.love --lovejs-path love.js --game-script game.js

      - name: Upload preview artifact
        uses: actions/upload-artifact@v4
        with:
          name: lovejs-preview
          path: build/lovejs
