name: Build love.js Preview

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Lua 5.1
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.1"
          buildCache: "false"

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Run Lua unit tests
        run: lua tests/run_tests.lua

      - name: Lint Lua sources
        run: find . -name '*.lua' -not -path './vendor/*' -print0 | xargs -0 -n1 luac -p

      - name: Prepare build directories
        run: |
          mkdir -p build
          mkdir -p build/lovejs

      - name: Create tactics battle .love archive
        run: |
          cd tactics_battle
          zip -9 -r ../build/tactics_battle.love .

      - name: Download love.js runtime
        run: |
          curl -L -o build/lovejs-runtime.zip https://github.com/TannerRogalsky/love.js/releases/download/11.4/love.js-11.4.zip
          unzip -o build/lovejs-runtime.zip -d build/lovejs

      - name: Move runtime assets
        run: |
          mv build/lovejs/love.js-11.4/* build/lovejs/
          rm -rf build/lovejs/love.js-11.4
          cp build/tactics_battle.love build/lovejs/game.love

      - name: Generate preview HTML shell
        run: lua ci_preview/generate_preview_html.lua --output build/lovejs/index.html --game-archive game.love --lovejs-path love.js

      - name: Upload preview artifact
        uses: actions/upload-artifact@v4
        with:
          name: lovejs-preview
          path: build/lovejs
